name: DeploymentTEST01

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: preprod
      url: https://fendisfoa--preprod.sandbox.lightning.sfcrmapps.cn
    steps:
      - name: deploy
        # ...deployment-specific steps
